import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 — Vimperk palette
        brand: {
          50: "#ffdad7",
          100: "#ffcec9",
          200: "#ffb3ae",
          300: "#ff978f",
          400: "#f56c67",
          500: "#da1e2d",
          600: "#c0001f",
          700: "#b2001c",
          800: "#930015",
          900: "#410004",
        },
        "secondary-fixed":           "#bdefbe",
        "surface-container-high":    "#e5e8ee",
        "surface":                   "#f7f9ff",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f1f4fa",
        "on-primary-fixed-variant":  "#930015",
        "on-primary-fixed":          "#410004",
        "inverse-primary":           "#ffb3ae",
        "tertiary-fixed":            "#d2e4ff",
        "surface-container-highest": "#dfe3e8",
        "primary-fixed-dim":         "#ffb3ae",
        "surface-tint":              "#c0001f",
        "tertiary-fixed-dim":        "#a1c9ff",
        "outline":                   "#8f6f6c",
        "on-primary-container":      "#fff2f0",
        "inverse-on-surface":        "#eef1f7",
        "surface-bright":            "#f7f9ff",
        "primary":                   "#b2001c",
        "on-tertiary":               "#ffffff",
        "tertiary":                  "#095999",
        "surface-container":         "#ebeef4",
        "on-tertiary-fixed":         "#001c37",
        "on-tertiary-fixed-variant": "#004880",
        "inverse-surface":           "#2d3135",
        "on-secondary-fixed-variant":"#24502c",
        "on-secondary":              "#ffffff",
        "on-surface-variant":        "#5b403d",
        "primary-container":         "#da1e2d",
        "on-surface":                "#181c20",
        "secondary-fixed-dim":       "#a2d3a4",
        "outline-variant":           "#e4beba",
        "on-background":             "#181c20",
        "on-secondary-fixed":        "#002109",
        "background":                "#f7f9ff",
        "secondary":                 "#3c6842",
        "primary-fixed":             "#ffdad7",
        "on-error":                  "#ffffff",
        "surface-variant":           "#dfe3e8",
        "error":                     "#ba1a1a",
        "error-container":           "#ffdad6",
        "secondary-container":       "#baecbb",
        "on-secondary-container":    "#406c46",
        "on-tertiary-container":     "#f0f4ff",
        "on-primary":                "#ffffff",
        "tertiary-container":        "#3372b4",
        "surface-dim":               "#d7dae0",
        "on-error-container":        "#93000a",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
        sans:     ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
